
package Vista;

import Usuario.Usuario;


public class Configuracion extends javax.swing.JFrame {
    public static String Dificultad="normal",MododeJuego= "aleatorio";
    int xMouse , yMouse;
    private MenuPrincipal aThis;
     Usuario UsuarioGLob ;
    
     
    public Configuracion(Usuario usu, MenuPrincipal aThis, boolean par) {
        initComponents();
        UsuarioGLob=usu;

        this.setLocationRelativeTo(null);
        this.aThis = aThis;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupodeDificultad = new javax.swing.ButtonGroup();
        GrupodeManualidades = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        btnDificultad = new javax.swing.JButton();
        btnModalidadJuego = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelMiPerfil = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Normal = new javax.swing.JRadioButton();
        Expert = new javax.swing.JRadioButton();
        Genius = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        dificult_rb5 = new javax.swing.JRadioButton();
        Aleatorio = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("ACEPTAR");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 70));

        btnDificultad.setBackground(new java.awt.Color(0, 0, 0));
        btnDificultad.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btnDificultad.setForeground(new java.awt.Color(255, 255, 255));
        btnDificultad.setText("DIFICULTAD");
        btnDificultad.setActionCommand("MODO DE JUEGO");
        btnDificultad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDificultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificultadActionPerformed(evt);
            }
        });
        jPanel4.add(btnDificultad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 220, 70));

        btnModalidadJuego.setBackground(new java.awt.Color(0, 0, 0));
        btnModalidadJuego.setFont(new java.awt.Font("Viner Hand ITC", 0, 20)); // NOI18N
        btnModalidadJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnModalidadJuego.setText("MODO DE JUEGO");
        btnModalidadJuego.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnModalidadJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModalidadJuegoActionPerformed(evt);
            }
        });
        jPanel4.add(btnModalidadJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 220, 70));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, 450));

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        jPanel8.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 460, 379));

        jLabel5.setFont(new java.awt.Font("Viner Hand ITC", 2, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CONFIGURACION");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 350, -1));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 480, 70));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        PanelMiPerfil.setBackground(new java.awt.Color(0, 0, 0));
        PanelMiPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelMiPerfilMouseClicked(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DIFICULTAD", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Japanese Robot", 0, 24))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(204, 0, 204));
        jPanel5.setToolTipText("");

        Normal.setBackground(new java.awt.Color(0, 0, 0));
        GrupodeDificultad.add(Normal);
        Normal.setFont(new java.awt.Font("Viner Hand ITC", 2, 36)); // NOI18N
        Normal.setForeground(new java.awt.Color(153, 153, 153));
        Normal.setText("normal");
        Normal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Normal.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NormalActionPerformed(evt);
            }
        });

        Expert.setBackground(new java.awt.Color(0, 0, 0));
        GrupodeDificultad.add(Expert);
        Expert.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        Expert.setForeground(new java.awt.Color(102, 102, 102));
        Expert.setText("expert");
        Expert.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Expert.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Expert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpertActionPerformed(evt);
            }
        });

        Genius.setBackground(new java.awt.Color(0, 0, 0));
        GrupodeDificultad.add(Genius);
        Genius.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        Genius.setForeground(new java.awt.Color(153, 153, 153));
        Genius.setText("genius");
        Genius.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Genius.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Normal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Expert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Genius, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Normal)
                .addGap(5, 5, 5)
                .addComponent(Expert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Genius)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMiPerfilLayout = new javax.swing.GroupLayout(PanelMiPerfil);
        PanelMiPerfil.setLayout(PanelMiPerfilLayout);
        PanelMiPerfilLayout.setHorizontalGroup(
            PanelMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMiPerfilLayout.createSequentialGroup()
                .addContainerGap(144, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        PanelMiPerfilLayout.setVerticalGroup(
            PanelMiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiPerfilLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", PanelMiPerfil);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MODO DE JUEGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Japanese Robot", 0, 24))); // NOI18N

        dificult_rb5.setBackground(new java.awt.Color(0, 0, 0));
        GrupodeManualidades.add(dificult_rb5);
        dificult_rb5.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        dificult_rb5.setForeground(new java.awt.Color(102, 102, 102));
        dificult_rb5.setText("MANUAL");
        dificult_rb5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dificult_rb5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        dificult_rb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificult_rb5ActionPerformed(evt);
            }
        });

        Aleatorio.setBackground(new java.awt.Color(0, 0, 0));
        GrupodeManualidades.add(Aleatorio);
        Aleatorio.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        Aleatorio.setForeground(new java.awt.Color(153, 153, 153));
        Aleatorio.setSelected(true);
        Aleatorio.setText("ALEATORIO");
        Aleatorio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Aleatorio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        Aleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AleatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dificult_rb5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Aleatorio, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(Aleatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificult_rb5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 260, 170));

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 460, 410));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed

        
        
          jTabbedPane1.setSelectedIndex(1);
        if (Normal.isSelected()) {
            Dificultad="normal";
            
            
        } else if (Expert.isSelected()) {
            Dificultad="expert";
            
             jTabbedPane1.setSelectedIndex(2);
        } else if (Genius.isSelected()) {
            Dificultad="genius";
        }
        System.out.println("Dificultad: " + Dificultad + " " + jTabbedPane1.getSelectedComponent()) ;
        jTabbedPane1.setSelectedIndex(2);
        if (Aleatorio.isSelected()) {
            MododeJuego="aleatorio";
        } else {
            MododeJuego="manual";
        }
        
        
        
        
        
        this.setVisible(false);
        MenuPrincipal frmpaginaPrincipal = new  MenuPrincipal (UsuarioGLob);
        frmpaginaPrincipal.setVisible(true);
        // MenuPrincipal.MiPerfil.setModal(true);
        //FRMPaginaPrincipal.MiPerfil.pack();
        //FRMPaginaPrincipal.MiPerfil.setLocationRelativeTo(this);
        //
        //dispose();
        //this.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void PanelMiPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelMiPerfilMouseClicked

    }//GEN-LAST:event_PanelMiPerfilMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
      
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NormalActionPerformed

    private void ExpertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpertActionPerformed

    private void AleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AleatorioActionPerformed

    private void dificult_rb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificult_rb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dificult_rb5ActionPerformed

    private void btnDificultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificultadActionPerformed
     
        jTabbedPane1.setSelectedIndex(1);
        if (Normal.isSelected()) {
            Dificultad="normal";
            
            
        } else if (Expert.isSelected()) {
            Dificultad="expert";
            
             jTabbedPane1.setSelectedIndex(2);
        } else if (Genius.isSelected()) {
            Dificultad="genius";
        }
        System.out.println("Dificultad: " + Dificultad + " " + jTabbedPane1.getSelectedComponent()) ;
        
        
        
    }//GEN-LAST:event_btnDificultadActionPerformed

    private void btnModalidadJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModalidadJuegoActionPerformed
        
        jTabbedPane1.setSelectedIndex(2);
        if (Aleatorio.isSelected()) {
            MododeJuego="aleatorio";
        } else {
            MododeJuego="manual";
        }
    }//GEN-LAST:event_btnModalidadJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Configuracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Configuracion(null,null, true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Aleatorio;
    private javax.swing.JRadioButton Expert;
    private javax.swing.JRadioButton Genius;
    private javax.swing.ButtonGroup GrupodeDificultad;
    private javax.swing.ButtonGroup GrupodeManualidades;
    private javax.swing.JRadioButton Normal;
    private javax.swing.JPanel PanelMiPerfil;
    private javax.swing.JButton btnDificultad;
    private javax.swing.JButton btnModalidadJuego;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JRadioButton dificult_rb5;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
