
package Vista;

import LogicaUsuario.UsuarioLogic;
import Usuario.Usuario;
import FiveCodMover.FiveCodMoverJDialog;
import java.util.Set;


import javax.swing.JDialog;
import javax.swing.JOptionPane;

public class MenuPrincipal extends javax.swing.JFrame {

    int xMouse, yMouse;
    public static Usuario UsuarioGLob;
    public static String Player2;
    private String Castillo[][];
    private int GhostsGp1 = 0, GhostsGp2 = 0, GhostsBp1 = 0, GhostsBp2 = 0, contador = 0;
    private char turnoJugador = 'L';
    private boolean victoria = false, colocadas = false;
    public String Dificultad = Configuracion.Dificultad, MododeJuego = Configuracion.MododeJuego;

   
    public MenuPrincipal(Usuario usuario) {
        initComponents();
        this.setLocationRelativeTo(null);

       
        lblUsuario.setText(usuario.getNombres());
        UsuarioGLob = usuario;
    }

    MenuPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Reportes = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        btnRanking = new javax.swing.JButton();
        btnRegresarMenuPrincipalReports = new javax.swing.JButton();
        btnEstadisticas = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        btnMoodJuego2 = new javax.swing.JButton();
        btnRegresarMenuPrincipal2 = new javax.swing.JButton();
        btnDificultad2 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        MiPerfil = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        btnElliminarcuenta = new javax.swing.JButton();
        RegresarMenu = new javax.swing.JButton();
        btnMisDatos = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        btnCambiarcontrasena1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnRConfiguracion = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        btnPerfil = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();

        Reportes.setUndecorated(true);
        Reportes.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                ReportesMouseDragged(evt);
            }
        });
        Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ReportesMousePressed(evt);
            }
        });
        Reportes.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/Fantasma-30.gif"))); // NOI18N
        Reportes.getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 319, -1));

        btnRanking.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnRanking.setText("Ranking de Jugadores");
        btnRanking.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRankingActionPerformed(evt);
            }
        });
        Reportes.getContentPane().add(btnRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 153, 416, 44));

        btnRegresarMenuPrincipalReports.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnRegresarMenuPrincipalReports.setText("Regresar al menú principal");
        btnRegresarMenuPrincipalReports.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarMenuPrincipalReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincipalReportsActionPerformed(evt);
            }
        });
        Reportes.getContentPane().add(btnRegresarMenuPrincipalReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 208, -1, 44));

        btnEstadisticas.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnEstadisticas.setText("Ultimos 10 juegos");
        btnEstadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        Reportes.getContentPane().add(btnEstadisticas, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 91, 416, 44));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/fantasma.gif"))); // NOI18N
        Reportes.getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 244, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/fantasma.gif"))); // NOI18N
        Reportes.getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 91, 244, -1));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/Fantasma-30.gif"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 319, -1));

        btnMoodJuego2.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnMoodJuego2.setText("Modo de juego");
        btnMoodJuego2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoodJuego2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoodJuego2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnMoodJuego2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 153, 416, 44));

        btnRegresarMenuPrincipal2.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnRegresarMenuPrincipal2.setText("Regresar al menú principal");
        btnRegresarMenuPrincipal2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresarMenuPrincipal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuPrincipal2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnRegresarMenuPrincipal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 208, -1, 44));

        btnDificultad2.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnDificultad2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDificultad2.setLabel("Dificultad");
        btnDificultad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificultad2ActionPerformed(evt);
            }
        });
        jPanel3.add(btnDificultad2, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 91, 416, 44));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/fantasma.gif"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 244, -1));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/fantasma.gif"))); // NOI18N
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 91, 244, -1));

        jLabel13.setFont(new java.awt.Font("Bubble Bobble", 0, 70)); // NOI18N
        jLabel13.setText("REPORTES");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 73));

        Reportes.getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        MiPerfil.setUndecorated(true);
        MiPerfil.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                MiPerfilMouseDragged(evt);
            }
        });
        MiPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MiPerfilMousePressed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/Fantasma-30.gif"))); // NOI18N
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 319, -1));

        btnElliminarcuenta.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnElliminarcuenta.setText("Eliminar cuenta");
        btnElliminarcuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnElliminarcuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElliminarcuentaActionPerformed(evt);
            }
        });
        jPanel4.add(btnElliminarcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 416, 44));

        RegresarMenu.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        RegresarMenu.setText("Regresar al menú principal");
        RegresarMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegresarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarMenuActionPerformed(evt);
            }
        });
        jPanel4.add(RegresarMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 44));

        btnMisDatos.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnMisDatos.setText("Mis Datos");
        btnMisDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMisDatosActionPerformed(evt);
            }
        });
        jPanel4.add(btnMisDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(259, 91, 416, 44));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/fantasma.gif"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 91, 244, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/recursos/Recursos/fantasma.gif"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 91, 244, -1));

        jLabel26.setFont(new java.awt.Font("Bubble Bobble", 0, 70)); // NOI18N
        jLabel26.setText("REPORTES");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, 73));

        btnCambiarcontrasena1.setFont(new java.awt.Font("Bubble Bobble", 0, 36)); // NOI18N
        btnCambiarcontrasena1.setText("Cambiar contraseña");
        btnCambiarcontrasena1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCambiarcontrasena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambiarcontrasena1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnCambiarcontrasena1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 416, 44));

        javax.swing.GroupLayout MiPerfilLayout = new javax.swing.GroupLayout(MiPerfil.getContentPane());
        MiPerfil.getContentPane().setLayout(MiPerfilLayout);
        MiPerfilLayout.setHorizontalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
            .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MiPerfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        MiPerfilLayout.setVerticalGroup(
            MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
            .addGroup(MiPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(MiPerfilLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Viner Hand ITC", 2, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU PRINCIPAL");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 460, 60));

        btnRConfiguracion.setBackground(new java.awt.Color(0, 0, 0));
        btnRConfiguracion.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btnRConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        btnRConfiguracion.setText("ConfiguraciOn");
        btnRConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnRConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRConfiguracionMouseClicked(evt);
            }
        });
        btnRConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRConfiguracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnRConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 250, 40));

        btnJugar.setBackground(new java.awt.Color(0, 0, 0));
        btnJugar.setFont(new java.awt.Font("Viner Hand ITC", 0, 36)); // NOI18N
        btnJugar.setForeground(new java.awt.Color(255, 255, 255));
        btnJugar.setText("JUGAR");
        btnJugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJugar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 230, 70));

        btnPerfil.setBackground(new java.awt.Color(0, 0, 0));
        btnPerfil.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Mi Perfil");
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 250, 40));

        btnRegresar.setBackground(new java.awt.Color(153, 153, 153));
        btnRegresar.setFont(new java.awt.Font("Viner Hand ITC", 0, 18)); // NOI18N
        btnRegresar.setText("CERRAR CESION");
        btnRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, 200, 30));

        btnReportes.setBackground(new java.awt.Color(0, 0, 0));
        btnReportes.setFont(new java.awt.Font("Viner Hand ITC", 0, 24)); // NOI18N
        btnReportes.setForeground(new java.awt.Color(255, 255, 255));
        btnReportes.setText("Reportes");
        btnReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 250, 40));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel5MouseDragged(evt);
            }
        });
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 50));

        lblUsuario.setFont(new java.awt.Font("Viner Hand ITC", 2, 24)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("User");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRConfiguracionActionPerformed
        this.hide();
        Configuracion frmconfiguracion = new Configuracion(UsuarioGLob, this, true);
        frmconfiguracion.setVisible(true);

//        Configuracion frmConfiguracion = new Configuracion();
//        frmConfiguracion.setVisible(true);
//        this.hide();
//        this.setVisible(false);
//        Configuraciones.setModal(true);
//        Configuraciones.pack();
//        Configuraciones.setLocationRelativeTo(this);
//        Configuraciones.setVisible(true);
    }//GEN-LAST:event_btnRConfiguracionActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        Player2 = JOptionPane.showInputDialog(this, "Ingrese el nombre del rival: ");
        if (UsuarioLogic.obtener(Player2) != null) {
            this.hide();
            Tablero Juego = new Tablero();
            Juego.setVisible(true);
            String posicion = "";
            Object boton = "";
            Juego.vaciarTablero();
            Juego.RespuertaTablero();
            Juego.getBotonStr(boton);
            Juego.boton(posicion);

            Juego.TableroAleatorio();

            GhostsGp1 = 0;
            GhostsBp1 = 0;
            GhostsGp2 = 0;
            GhostsGp2 = 0;

            contador = 0;
            victoria = false;
            colocadas = false;
            turnoJugador = 'L';
        } else {
            JOptionPane.showMessageDialog(this, "El usuario ingresado no existe");
        }

    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerfilActionPerformed
        // TODO add yourR handling code here:
        this.hide();
        MiPerfil frmmiperfil = new MiPerfil(UsuarioGLob, this, true);
        frmmiperfil.setVisible(true);

        /*this.setVisible(false);
        MiPerfil.setModal(true);
        MiPerfil.pack();
        MiPerfil.setLocationRelativeTo(this);
        MiPerfil.setVisible(true);*/
    }//GEN-LAST:event_btnPerfilActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Loging frm = new Loging();
        frm.show();
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        this.hide();
        Reportes frmreportes = new Reportes(UsuarioGLob, this, true);
        frmreportes.setVisible(true);
        // this.setVisible(false);
        //Reportes.setModal(true);
        //Reportes.pack();
//        Reportes.setLocationRelativeTo(this);
//        Reportes.setVisible(true);
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnRConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRConfiguracionMouseClicked
        // TODO add your handling code here:
        // Configuraciones.setVisible(true);
    }//GEN-LAST:event_btnRConfiguracionMouseClicked

    private void btnRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRankingActionPerformed

    private void btnRegresarMenuPrincipalReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincipalReportsActionPerformed
        // TODO add your handling code here:
        /*Reportes.setVisible(false);
        this.setVisible(true);*/
    }//GEN-LAST:event_btnRegresarMenuPrincipalReportsActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnMoodJuego2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoodJuego2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMoodJuego2ActionPerformed

    private void btnRegresarMenuPrincipal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuPrincipal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarMenuPrincipal2ActionPerformed

    private void btnDificultad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificultad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDificultad2ActionPerformed

    private void btnElliminarcuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElliminarcuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnElliminarcuentaActionPerformed

    private void RegresarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarMenuActionPerformed
        MiPerfil.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_RegresarMenuActionPerformed

    private void btnMisDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMisDatosActionPerformed
        /*this.hide();
        MiPerfil frmmiperfil = new MiPerfil(UsuarioGLob, this, true);
        MiPerfil.setVisible(false);
        frmmiperfil.setVisible(true);
        /*
        MiPerfil frmmiperfil = new MiPerfil(UsuarioLogic.obtener(txtUsuario.getText()));
        frmPaginaprincipal.setVisible(true);
         */
    }//GEN-LAST:event_btnMisDatosActionPerformed

    private void btnCambiarcontrasena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambiarcontrasena1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambiarcontrasena1ActionPerformed

    private void jPanel5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jPanel5MousePressed

    private void jPanel5MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();

        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_jPanel5MouseDragged

    private void ReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMousePressed
        FiveCodMoverJDialog.MousePressed(evt);
    }//GEN-LAST:event_ReportesMousePressed

    private void ReportesMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportesMouseDragged
        FiveCodMoverJDialog.MouseDraggedJDialog(evt, Reportes);
    }//GEN-LAST:event_ReportesMouseDragged

    private void MiPerfilMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiPerfilMousePressed
        FiveCodMoverJDialog.MousePressed(evt);
    }//GEN-LAST:event_MiPerfilMousePressed

    private void MiPerfilMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MiPerfilMouseDragged
        FiveCodMoverJDialog.MouseDraggedJDialog(evt, MiPerfil);
    }//GEN-LAST:event_MiPerfilMouseDragged

   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal(UsuarioGLob).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDialog MiPerfil;
    private javax.swing.JButton RegresarMenu;
    public static javax.swing.JDialog Reportes;
    private javax.swing.JButton btnCambiarcontrasena1;
    private javax.swing.JButton btnDificultad2;
    private javax.swing.JButton btnElliminarcuenta;
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnMisDatos;
    private javax.swing.JButton btnMoodJuego2;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JButton btnRConfiguracion;
    private javax.swing.JButton btnRanking;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRegresarMenuPrincipal2;
    private javax.swing.JButton btnRegresarMenuPrincipalReports;
    private javax.swing.JButton btnReportes;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
